{"name": "Test Error Response Handling", "status": "passed", "description": "Verifica que la función getData maneja correctamente una respuesta HTTP con error (código 404), devuelve False y no crea un archivo Excel.", "attachments": [{"name": "stdout", "source": "0867d7a1-5373-4e5d-bd19-66e658b41645-attachment.txt", "type": "text/plain"}], "start": 1744782968420, "stop": 1744782968421, "uuid": "a3f94756-d662-4f53-9250-98220cdf731f", "historyId": "0a9e3d2e0034700df046cdad666c7a8f", "testCaseId": "0a9e3d2e0034700df046cdad666c7a8f", "fullName": "tests.test_02_request#test_error_response", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "unit"}, {"name": "feature", "value": "Data Request System"}, {"name": "tag", "value": "request"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_02_request"}, {"name": "host", "value": "emanuelZuluaga"}, {"name": "thread", "value": "26332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_02_request"}]}