{"name": "Test Data Analysis with File Not Found", "status": "passed", "description": "Verifica que el método AnalizeData lanza FileNotFoundError cuando el archivo de datos no existe. El módulo debería mejorar el manejo de este error.", "attachments": [{"name": "stdout", "source": "6bfd3f59-8e3f-4f5d-b47f-d6bd3e5044f8-attachment.txt", "type": "text/plain"}], "start": 1744782968998, "stop": 1744782968998, "uuid": "d5d29c74-4c0b-4e67-afe2-d7a7e6d7e5a2", "historyId": "ae85159b7a8117e01000f6122354d0d2", "testCaseId": "ae85159b7a8117e01000f6122354d0d2", "fullName": "tests.test_03_analytics#test_analyze_data_file_not_found", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "tag", "value": "unit"}, {"name": "tag", "value": "analytics"}, {"name": "feature", "value": "Data Analytics System"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_03_analytics"}, {"name": "host", "value": "emanuelZuluaga"}, {"name": "thread", "value": "26332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_03_analytics"}]}